name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: check the deployed service url
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fso-pokedex-cicd.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
